import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import { createApp } from '../server/custodian.js';
import { generateIssuerKeys } from '../src/filings.js';
const server = createApp({ keys: generateIssuerKeys() }).listen(0, '127.0.0.1');
await new Promise<void>(resolve => server.once('listening', resolve));
const address = server.address(); if (!address || typeof address === 'string') throw Error('No test port');
const base = `http://127.0.0.1:${address.port}`;
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
page.setDefaultTimeout(180000);
const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
mkdirSync('proof-artifacts', { recursive: true });
try {
  await page.goto(base);
  await page.locator('#filingSelect option').first().waitFor({ state: 'attached' });
  assert.equal(await page.locator('#exportBtn').isVisible(), false);
  await page.locator('#askBtn').click();
  await page.waitForFunction(() => document.querySelector('#agencyOutput')?.textContent?.includes('NOT REGISTERED'));
  await page.locator('#loadFilingBtn').click();
  await page.waitForFunction(() => document.querySelector('#dofOutput')?.textContent?.includes(' registered.'));
  await page.locator('#askBtn').click();
  await page.locator('#agencyOutput .answer').waitFor();
  assert.equal(await page.locator('#agencyOutput .answer').textContent(), 'YES');
  const downloadEvent = page.waitForEvent('download'); await page.locator('#exportBtn').click();
  const download = await downloadEvent; await download.saveAs('proof-artifacts/browser-answer.json');
  await page.locator('#verifyBtn').click();
  await page.waitForFunction(() => document.querySelector('#verifyOutput')?.textContent?.startsWith('VERIFIED.'));
  await page.screenshot({ path: 'proof-artifacts/demo-desktop.png', fullPage: true });
  await page.locator('#tamperBtn').click();
  await page.waitForFunction(() => document.querySelector('#verifyOutput')?.textContent?.includes('Changed-answer test: REJECTED'));
  await page.locator('#bundleFile').setInputFiles('proof-artifacts/browser-answer.json');
  await page.waitForFunction(() => document.querySelector('#verifyOutput')?.textContent?.startsWith('VERIFIED.'));
  console.log('PASS browser Q001 YES, public export, imported verification and changed-answer rejection');
  await page.locator('#filingSelect').selectOption('DEMO-RPIE-001-2025-BELOW-COUNT');
  assert.equal(await page.locator('#exportBtn').isVisible(), false);
  await page.locator('#loadFilingBtn').click();
  await page.waitForFunction(() => document.querySelector('#dofOutput')?.textContent?.includes('2025-BELOW-COUNT registered'));
  await page.locator('#askBtn').click(); await page.locator('#agencyOutput .answer').waitFor();
  assert.equal(await page.locator('#agencyOutput .answer').textContent(), 'NO');
  console.log('PASS browser Q001 NO');
  await page.locator('#questionSelect').selectOption('Q002');
  await page.locator('#filingSelect').selectOption('DEMO-RPIE-001-2025-STRESS');
  await page.locator('#loadFilingBtn').click();
  await page.waitForFunction(() => document.querySelector('#dofOutput')?.textContent?.includes('2025-STRESS registered'));
  await page.locator('#loadPriorBtn').click();
  await page.waitForFunction(() => document.querySelector('#dofOutput')?.textContent?.includes('2024-BASE registered'));
  await page.locator('#askBtn').click(); await page.locator('#agencyOutput .answer').waitFor();
  assert.equal(await page.locator('#agencyOutput .answer').textContent(), 'YES');
  console.log('PASS browser Q002 prior registration and genuine cross-year YES');
  await page.locator('#priorSelect').selectOption('DEMO-RPIE-001-2024-ZERO');
  await page.locator('#loadPriorBtn').click();
  await page.waitForFunction(() => document.querySelector('#dofOutput')?.textContent?.includes('2024-ZERO registered'));
  await page.locator('#askBtn').click();
  await page.waitForFunction(() => document.querySelector('#agencyOutput')?.textContent?.includes('UNAVAILABLE'));
  assert.equal(await page.locator('#exportBtn').isVisible(), false);
  await page.locator('#filingSelect').selectOption('DEMO-RPIE-001-2025-INCOMPLETE');
  await page.locator('#loadFilingBtn').click();
  await page.waitForFunction(() => document.querySelector('#dofOutput')?.textContent?.includes('Registration rejected'));
  console.log('PASS browser nonpositive prior and incomplete source fail closed');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: 'proof-artifacts/demo-mobile.png', fullPage: true });
  const disclosures = await (await fetch(`${base}/api/disclosures`)).json();
  assert(disclosures.some((x: any) => x.status === 'verified_yes'));
  assert.doesNotMatch(JSON.stringify(disclosures), /salt|income|expenses|regulated_units_reported/);
  assert.deepEqual(errors, []);
  console.log('PASS responsive layout, disclosure log and no browser runtime errors');
} finally {
  await browser.close();
  await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
}
